package com.lpoo.atividade06;

import java.awt.Frame;
import java.util.ArrayList;
import java.util.List;
import javax.swing.SwingUtilities;

public class LivroAutorView extends javax.swing.JPanel {

    private List<Autor> autores;
    private AutorDAO autorDAO;
    
    private List<Livro> livros;
    private LivroDAO livroDAO;

    /**
     * Creates new form LivroAutorView
     */
    public LivroAutorView() {
        initComponents();
        configurarTabelaAutor();
        configurarTabelaLivro();
        autorDAO = new AutorDAO();
        livroDAO = new LivroDAO();
    }

    private void configurarTabelaAutor() {
        AutorTableModel autorTableModel = new AutorTableModel(new ArrayList<>());
        tabelaAutor.setModel(autorTableModel);

        atualizarTabelaAutor();
    }

    private void atualizarTabelaAutor() {
        AutorDAO autorDAO = new AutorDAO();
        List<Autor> autores = autorDAO.listarAutores();

        AutorTableModel autorTableModel = (AutorTableModel) tabelaAutor.getModel();
        autorTableModel.setAutores(autores);
    }
    
    private void configurarTabelaLivro() {
        LivroTableModel livroTableModel = new LivroTableModel(new ArrayList<>());
        tabelaLivro.setModel(livroTableModel);

        atualizarTabelaLivro();
    }

    private void atualizarTabelaLivro() {
        LivroDAO livroDAO = new LivroDAO();
        List<Livro> livros = livroDAO.listarLivroComAutores();

        LivroTableModel livroTableModel = (LivroTableModel) tabelaLivro.getModel();
        livroTableModel.setLivros(livros);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnAutor = new javax.swing.JButton();
        btnLivro = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAutor = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaLivro = new javax.swing.JTable();

        setLayout(new java.awt.GridBagLayout());

        btnAutor.setText("Incluir autor");
        btnAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 52, 0, 0);
        add(btnAutor, gridBagConstraints);

        btnLivro.setText("Incluir livro");
        btnLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLivroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 163, 0, 0);
        add(btnLivro, gridBagConstraints);

        tabelaAutor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaAutor);

        jScrollPane2.setViewportView(jScrollPane1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 447;
        gridBagConstraints.ipady = 82;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 6);
        add(jScrollPane2, gridBagConstraints);

        tabelaLivro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabelaLivro);

        jScrollPane4.setViewportView(jScrollPane3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 447;
        gridBagConstraints.ipady = 99;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        add(jScrollPane4, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutorActionPerformed
        AutorFormView dialog = new AutorFormView((Frame) SwingUtilities.getWindowAncestor(this));
        dialog.setVisible(true);
        
        atualizarTabelaAutor();
    }//GEN-LAST:event_btnAutorActionPerformed

    private void btnLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLivroActionPerformed
        List<Autor> autores = autorDAO.listarAutores();
        
        LivroFormView dialog = new LivroFormView((Frame) SwingUtilities.getWindowAncestor(this), autores);
        dialog.setVisible(true);
        
        atualizarTabelaLivro();
    }//GEN-LAST:event_btnLivroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutor;
    private javax.swing.JButton btnLivro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tabelaAutor;
    private javax.swing.JTable tabelaLivro;
    // End of variables declaration//GEN-END:variables
}
